---

- name: Select Project
  command: "oc project {{ namespace }}"

- name: Delete timer deployment
  k8s_extensions_v1beta1_deployment:
    name: timer
    namespace: "{{ namespace }}"
    state: absent

- name: Delete storagesvc deployment
  k8s_extensions_v1beta1_deployment:
    name: storagesvc
    namespace: "{{ namespace }}"
    state: absent

- name: Delete kubewatcher deployment
  k8s_extensions_v1beta1_deployment:
    name: kubewatcher
    namespace: "{{ namespace }}"
    state: absent

- name: Delete buildermgr deployment
  k8s_extensions_v1beta1_deployment:
    name: buildermgr
    namespace: "{{ namespace }}"
    state: absent

- name: Delete poolmgr deployment
  k8s_extensions_v1beta1_deployment:
    name: poolmgr
    namespace: "{{ namespace }}"
    state: absent

- name: Delete controller deployment
  k8s_extensions_v1beta1_deployment:
    name: controller
    namespace: "{{ namespace }}"
    state: absent

- name: Delete router deployment
  k8s_extensions_v1beta1_deployment:
    name: router
    namespace: "{{ namespace }}"
    state: absent

- name: Delete router route
  openshift_v1_route:
    name: router
    namespace: "{{ namespace }}"
    state: absent

- name: Delete Router Service
  k8s_v1_service:
    name: router
    state: absent
    namespace: "{{ namespace }}"

- name: Delete controller route
  openshift_v1_route:
    name: controller
    namespace: "{{ namespace }}"
    state: absent

- name: Delete Controller Service
  k8s_v1_service:
    name: controller
    state: absent
    namespace: "{{ namespace }}"

- name: Delete Storage Service
  k8s_v1_service:
    name: storagesvc
    state: absent
    namespace: "{{ namespace }}"

- name: Delete admin Role Binding
  k8s_v1beta1_role_binding:
    name: fission-admin
    namespace: "{{ namespace }}"
    state: absent
    namespace: "{{ namespace }}"

- name: Delete function Role Binding
  k8s_v1beta1_role_binding:
    name: fission-function-admin
    namespace: "{{ namespace }}"
    state: absent

- name: Delete crd Role Binding
  k8s_v1beta1_cluster_role_binding:
    name: fission-crd
    state: absent

- name: Delete fetcher Service Account
  k8s_v1_service_account:
    name: fission-fetcher
    namespace: "{{ functionNamespace }}"
    state: absent

- name: Delete fetcher Role Binding
  k8s_v1beta1_cluster_role_binding:
    name: fission-fetcher-crd
    state: absent

- name: Delete builder Service Account
  k8s_v1_service_account:
    name: fission-builder
    namespace: "{{ builderNamespace }}"
    state: absent

- name: Delete builder Role Binding
  k8s_v1beta1_cluster_role_binding:
    name: fission-builder-crd
    state: absent

- name: Delete poolmgr Service
  k8s_v1_service:
    name: poolmgr
    namespace: "{{ namespace }}"
    state: absent

- name: Delete buildermgr Service
  k8s_v1_service:
    name: buildermgr
    namespace: "{{ namespace }}"
    state: absent

- name: Delete svc Service Account
  k8s_v1_service_account:
    name: fission-svc
    state: absent
    namespace: "{{ namespace }}"

- name: Delete Function Namespace
  k8s_v1_namespace:
    name: "{{ functionNamespace }}"
    state: absent

- name: Delete Builder Namespace
  k8s_v1_namespace:
    name: "{{ builderNamespace }}"
    state: absent
